version: '3.1'

services:
  shop_api:
    image: shop/shop:0.1.0-SNAPSHOT
    ports:
      - "5000:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://shop_database:5432/shop"
      PRODUCTS_SERVICE_AVAILABLE: "true"
    depends_on:
      - shop_database

  shop_database:
    image: postgres:9.6.4
    ports:
        - "5432:5432"
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres